---

- name: Check user variable
  fail:
    msg: "user variable must be given"
  when: user is undefined

- name: Install from apt
  become: true
  apt:
    name: vim
    state: present

# Copy .vimrc only if not present
- name: Check existence of .vimrc
  stat:
    path: "/home/{{ user }}/.vimrc"
  register: vimrc

- name: Copy vimrc
  copy:
    src: .vimrc
    dest: "/home/{{ user }}/.vimrc"
  when: not vimrc.stat.exists


# Install and setup vim-plug plugin manager
- name: Create vim autoload folder
  file:
    path: "/home/{{ user }}/.vim/autoload"
    state: directory
  register: vim_autoload_dir

- name: Download vim-plug
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "{{ vim_autoload_dir.path }}"
